# 2014 SKWoolf bcnskaa AT gmail DOT com

import os.path
import sys
import getopt
from collections import defaultdict


# Require biopython
# To run this script, path to biopython libraries has to be included in PYTHONPATH
from Bio import SeqIO
from Bio.Seq import Seq





# Path to circos
CIRCOS_HOME="~/tools/circos/"



def main(argv):
    
    # Get current working directory
    CUR_WD = os.getcwd()
    print_status("Current Working Directory: " + CUR_WD)
    
    read_1_fn = argv[0]
    read_2_fn = argv[1]
    
    
    
    

# Print the usage of this script 
def print_usage():
    print("A utility for generating Circos diagram.")
    print(" ")
    print("Usage:")
    print(" python " + sys.argv[0] + " READ_1.fq READ_2.fq [OUTPUT_PREFIX]")
    #print("  python -i BLAST-RESULT-INFILE -o FILTER-OUTFILE [-q] [-b BITSCORE-CUTOFF] [-l ALIGNMENT-LENGTH-CUTOFF] [-p PERCENTAGE-IDENTITY]")
    #print("      -i STRING  Input file generated by BLAST with -m6 option")
    print(" ")
    print(" ") 
    print("Ver 0.2b")
   


# Print status
def print_status(msg):
    caller_name = inspect.stack()[1][3]
    msg = "[ " + caller_name + " ] " + datetime.now().strftime('%Y-%m-%d %H:%M:%S') + "  " + msg
    print(msg)
    
    

# Invoke the main function
if __name__ == "__main__":
    main(sys.argv[1:])